feat(FA-56): categorize image/video by upload status
S1ckret-Labs/family-archive-spa pull request #17
Opened 2023-08-29 11:00 UTC by G2p1

Closes #6

2023-08-29 14:37 UTC, s1ckret requested changes
What if a user uploads files? Will they be sorted.

> Note: We discussed it in meet. Just do a list and update statuses. Do not shuffle lines around to ease UX

2023-08-31 10:53 UTC, G2p1 commented on src/components/UploadSection.svelte
> +                    }
i dont know why, but i commited it earlier and git think that its another things, so i dont undarstand why is git put it here

2023-08-31 10:57 UTC, G2p1 commented on src/components/UploadSection.svelte
> +                uploadedFiles.push(pickedFile);
![image](https://github.com/S1ckret-Labs/family-archive-spa/assets/52936598/6c35e258-866e-49d0-8df7-9715faece0ac)
after we pick file(the last ine what pending upload)
![image](https://github.com/S1ckret-Labs/family-archive-spa/assets/52936598/874ce6a6-60ba-4ec9-93f1-82ed581dedfb)
and after 1 minute when file is uploaded

2023-08-31 14:01 UTC, s1ckret requested changes

2023-08-31 14:01 UTC, s1ckret commented on src/components/UploadSection.svelte
> +                uploadedFiles.push(pickedFile);
Why are we parsing exif data twice? Can't we populate the `uploadedFiles` array before?
I definitely need to draw a sequence diagram :)

2023-08-31 14:01 UTC, s1ckret commented on src/components/UploadSection.svelte
> +                }
All good. You can also use `for of` loop, because we don't need indexes. We don't perform any complex access patterns.
```
for (const element of theArray) {
    // ...use `element`...
}
```

2023-09-14 14:20 UTC, s1ckret approved these changes

2023-09-14 14:48 UTC, merged